name: Multi-Platform Build

on:
  push:
    branches:
      - main

#    tags:
#      - '*'

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
        sudo apt-get install -y libasound2-dev
    - run: flutter config --enable-linux-desktop
    - run: flutter pub get
    - name: Build Linux
      run: |
        flutter build linux --dart-define=isTV=false --release
        cd build/linux/x64/release/bundle
        zip -r easyTV-${{ github.ref_name }}-linux.zip *

    - name: Upload linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-artifact
        path: |
          build/linux/x64/release/bundle/easyTV-${{ github.ref_name }}-linux.zip

  create_release:
    needs: [build_linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact artifact
        uses: actions/download-artifact@v4
        with:
          path: release
          merge-multiple: true
      - name: display Release dir
        run: |
          realpath release  
          ls -l release

      - name: Upload artifacts to Release
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: |
            easy_tv_live/easy_tv_live/release/easyTV-${{ github.ref_name }}-linux.zip
          



